config/routes.rb
Rails.application.routes.draw do
root to: "books#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    get "reviews", to: "users#user_reviews"
    get "subscriptions_reviews", to: "users#subscriptions_reviews"
    resources :lists
    get :followers, :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show] do
    resources :reviews, except: [:show]
  end
  resources :authors, only: [:show]
  resources :book_lists, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]

  namespace :admin do
    root to: "books#index"
    resources :books
    resources :users
    resources :authors
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :book_lists, dependent: :destroy
  has_many :books, through: :book_lists

  validates :name, presence: true, length: {minimum: 2, maximum: 30}
  validates_uniqueness_of :name, scope: :user
  validates :user, presence: true

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @lists = @user.lists
  end

  def show

  end

  def new
    @list = @user.lists.build
  end

  def edit
  end

  def create
    @list = @user.lists.build(list_params)
    if @list.save
      redirect_to user_lists_path(@user.id), notice: 'Список создан.'
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to user_lists_path(@user.id), notice: 'Список редактирован.'
    else
      render :edit
    end
  end

  def destroy
    @list = @user.lists.find(params[:id])
    @list.destroy
    redirect_to user_lists_url(@user.id), notice: 'Список удалён.'
  end

  private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
.container-list
  = form_for [@user, @list] do |form|
    .field
      = form.label "Название"
      = form.text_field :name, maxlength: 30
    .actions.mt-4
      = form.submit "Создать", class: "btn btn-primary center"

app/views/lists/edit.html.haml
.row
  .col-6
    = render partial: "users/profile", locals: { user: @user }
  .col-6
    %h1.hmb Редактировать список
    = render 'form', list: @list

app/views/lists/index.html.haml
.row
  .col-6
    = render partial: "users/profile", locals: { user: @user }
  .col-6
    %h1.hmb Списки
    .mb-4.ml-3
      - @lists.each do |list|
        .list-line
          .list-name-block
            = link_to "#{list.name}", user_list_path(@user.id, list)
          - if can? :manage, list
            .list-icon-block
              = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_list_path(@user.id, list), title: "Редактировать"
              = link_to '<i class="fa fa-trash"></i>'.html_safe, user_list_path(@user.id, list), method: :delete, data: { confirm: 'Вы уверены' }, title: "Удалить"

    - if user_has_rights?(@user)
      = link_to 'Новый список',  new_user_list_path(current_user), class: "btn btn-primary border new-list-btn"

app/views/lists/new.html.haml
.row
  .col-6
    = render partial: "users/profile", locals: { user: @user }
  .col-6
    %h1.hmb Новый список
    = render 'form'

app/views/lists/show.html.haml
.row
  .col-6
    = render partial: "users/profile", locals: { user: @user }
  .col-6
    %h1= @list.name
    .mb-2.ml-3
      - if @list.book_lists.empty?
        %p Список пуст
      -else
        - @list.book_lists.each do |book_list|
          .list-book-line
            .list-book-name
              = link_to "#{book_list.book.title}", book_path(book_list.book)
            - if user_has_rights?(@user)
              = link_to '<i class="fa fa-trash"></i>'.html_safe, book_list_path(book_list), method: :delete