config/routes.rb
Rails.application.routes.draw do
root to: "books#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    get "reviews", to: "users#user_reviews"
    get "subscriptions_reviews", to: "users#subscriptions_reviews"
    resources :lists
    get :followers, :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show] do
    resources :reviews, except: [:show]
  end
  resources :authors, only: [:show]
  resources :book_lists, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]

  namespace :admin do
    root to: "books#index"
    resources :books
    resources :users
    resources :authors
  end
end

app/views/shared/_form_errors.html.haml
- content_for :form_errors do
  - if object.errors.any?
    #error_explanation
      %h3
        #{pluralize(object.errors.count, t('error', :count => object.errors.count))}:
        = t('activerecord.errors.messages.not_saved', :count => object.errors.count)

      %ul
        - object.errors.full_messages.each do |message|
          %li= message

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.bg-nav-custom
  .container
    %a.navbar-brand
      =link_to (image_tag('logo.png', class: "brand-img")), books_path
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to'<i class="fa fa-book ni"></i>Книги BLM'.html_safe , books_path, class: "nav-link"



        %li.nav-item
          = link_to '<i class="fa fa-users ni"></i>Пользователи'.html_safe , users_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to '<i class="fa fa-list ni"></i>Ваш список'.html_safe, user_lists_path(current_user), class: "nav-link"

        %li.nav-item
          .dropdown
            %a.nav-link.dropdown-toggle{"href" => "#", "id" => "navbarDropdown", "role" => "button", "data-toggle" => "dropdown", "aria-haspopup" => "true","aria-expanded" => "false"}#{'<i class="fa fa-user ni"></i>'.html_safe}Профиль
            .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
              - if user_signed_in?
                = link_to 'Профиль', user_path(current_user), class: "dropdown-item"
                = link_to 'Изменить профиль', edit_user_registration_path, class: "dropdown-item"
                = link_to 'Выйти', destroy_user_session_path, :method => :delete, class: "dropdown-item"
              - else
                = link_to 'Зарегистрироваться', new_user_registration_path, class: "dropdown-item"
                = link_to 'Войти', new_user_session_path, class: "dropdown-item"

app/views/shared/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "BLM", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Книги BLM', admin_books_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Авторы', admin_authors_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= new_object(controller.controller_name) %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>