config/routes.rb
Rails.application.routes.draw do
root to: "books#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    get "reviews", to: "users#user_reviews"
    get "subscriptions_reviews", to: "users#subscriptions_reviews"
    resources :lists
    get :followers, :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show] do
    resources :reviews, except: [:show]
  end
  resources :authors, only: [:show]
  resources :book_lists, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]

  namespace :admin do
    root to: "books#index"
    resources :books
    resources :users
    resources :authors
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :lists, dependent: :destroy
#подписчики
  has_many :follower_relationships, class_name: 'Follow', foreign_key: :followed_user_id
  has_many :followers, through: :follower_relationships
#подписки
  has_many :subscription_relationships, class_name: 'Follow', foreign_key: :follower_id
  has_many :subscriptions, through: :subscription_relationships


  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :username, :email, presence: true
  validates :email, uniqueness: true

  def follow(another_user_id)
    subscription_relationships.create(followed_user_id: another_user_id)
  end
 
  def unfollow(another_user_id)
    subscription_relationships.find_by(followed_user_id: another_user_id).destroy
  end

  def following?(another_user)
    subscriptions.include?(another_user)
  end

  def follower?(another_user)
    followers.include?(another_user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show]
  before_action :set_user_id, only: [:followers, :subscriptions, :user_reviews, :subscriptions_reviews]

  def index
    if params[:search].present?
      @users = User.where("lower(username) LIKE ?", "%#{params[:search].downcase}%")
    else
      @users = User.all
    end
  end

  def show
    if @user == current_user
      subscriptions_reviews
      render "subscriptions_reviews"
    else
      user_reviews
      render "user_reviews"
    end
  end

  def user_reviews
    @reviews = @user.reviews
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def set_user_id
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :set_user_id, only: [:followers, :subscriptions, :user_reviews, :subscriptions_reviews]

  def index
    if params[:search].present?
      @users = User.where("lower(username) LIKE ?", "%#{params[:search].downcase}%")
    else
      @users = User.all
    end
  end

  def show
    if @user == current_user
      subscriptions_reviews
      render "subscriptions_reviews"
    else
      user_reviews
      render "user_reviews"
    end
  end

  def followers
    @followers = @user.followers
  end

  def subscriptions
    @subscriptions = @user.subscriptions
  end

  def user_reviews
    @reviews = @user.reviews
  end

  def subscriptions_reviews
    @reviews = Review.where("user_id IN (?)", @user.subscriptions.ids).lately
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def set_user_id
    @user = User.find(params[:user_id])
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_profile.html.haml
%h1.hmb= user.username
.pl-3
  = link_to "Списки пользователя", user_lists_path(user.id)
  %br/
  = link_to "Подписчики", user_followers_path(user.id)
  %br/
  = link_to "Подписки", user_subscriptions_path(user.id)
  %br/
  = link_to "Отзывы пользователя", user_reviews_path(user.id)
  %br/
  - if user_has_rights?(user)
    = link_to "Отзывы подписчиков", user_subscriptions_reviews_path(user.id)
  %br/

app/views/admin/users/_user.html.haml
.user-line
  .user-link-block
    = link_to "#{user.username}", user_path(user)
  - if user_signed_in?
    .block-with-btn
      - if current_user != user
        - if current_user.following?(user)
          = link_to 'Отписаться', follow_path(user.id), method: :delete, class: "btn btn-red follow-btn"
        - else
          = link_to 'Подписаться', follows_path(follower_id: user.id), method: :post, class: "btn btn-primary follow-btn"

app/views/admin/users/followers.html.haml
.row
  .col-6
    = render partial: "profile", locals: { user: @user }
  .col-6
    %h1.hmb Подписчики
    - if @followers.empty?
      - if user_has_rights?(@user)
        %p У вас нету подписчиков.
      - else
        %p У #{@user.username} нету подписчиков.
    - else
      .scroll-block
        .users-container
          = render partial: "user", collection: @followers

app/views/admin/users/index.html.haml
.title-with-form.hmb
  %h1 Пользователи BLM
  = form_tag users_path, method: "get" do
    = text_field_tag :search, params[:search]
    = submit_tag "Искать пользователя", class: "btn btn-primary"
.row
  .col-6
    .picture
      =image_tag "2.png"
  .col-6
    .scroll-block
      .users-container
        = render partial: "user", collection: @users

app/views/admin/users/subscriptions.html.haml
.row
  .col-6
    = render partial: "profile", locals: { user: @user }
  .col-6
    %h1.hmb Подписки
    - if @subscriptions.empty?
      - if user_has_rights?(@user)
        %p У вас нету подписок.
      - else
        %p У #{@user.username} нету подписок.
    - else
      .scroll-block
        .users-container
          = render partial: "user", collection: @subscriptions

app/views/admin/users/subscriptions_reviews.html.haml
.row
  .col-6
    = render partial: "profile", locals: { user: @user }
  .col-6
    %h1.hmb Отзывы подписчиков
    - if @reviews.empty?
      %p Отзывов подписчиков нету.
    - else
      = render partial: 'reviews/review', collection: @reviews

app/views/admin/users/user_reviews.html.haml
.row
  .col-6
    = render partial: "profile", locals: { user: @user }
  .col-6
    %h1.hmb Ваши отзывы
    - if @reviews.empty?
      - if user_has_rights?(@user)
        %p Вы не оставили ни одного отзыва.
      - else
        %p #{@user.username} не оставил ни одного отзыва.
    - else
      = render partial: 'reviews/review', collection: @reviews