config/routes.rb
Rails.application.routes.draw do
root to: "books#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    get "reviews", to: "users#user_reviews"
    get "subscriptions_reviews", to: "users#subscriptions_reviews"
    resources :lists
    get :followers, :subscriptions
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:index, :show] do
    resources :reviews, except: [:show]
  end
  resources :authors, only: [:show]
  resources :book_lists, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy]

  namespace :admin do
    root to: "books#index"
    resources :books
    resources :users
    resources :authors
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book

  def index
    @reviews = @book.reviews
  end

  def new
    @review = @book.reviews.build
  end

  def edit

  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.book = @book
    if @review.save
      redirect_to @book, notice: 'Отзыв опубликован.'
    else
      render :new
    end
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book.id), notice: 'Отзыв обновлён.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book.id), notice: 'Отзыв удалён.'
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def review_params
      params.require(:review).permit(:body, :rating, :user_id, :book_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def your_review_title(user)
		if current_user == user 
			"Ваши отзывы"
		else 
		  "Отзывы #{user.username}" 
		end
	end
end

app/views/reviews/_form.html.haml
.review-form
  - if user_signed_in?
    = form_for [@book, @review] do |form|
      -form_errors_for(@review)
      .field
        = form.text_area :body, class: "review-text-block"
      .field.rating_block
        = form.label "Оценка: "
        = form.select :rating, Review::RATING
      .action
      - if controller.action_name == "new"
        = form.submit "Оставить отзыв", class: "btn btn-primary"
      - else
        = form.submit "Редактировать отзыв", class: "btn btn-primary"

app/views/reviews/_review.html.haml
- unless controller.controller_name == "books" || (controller.controller_name == "reviews" && action_name == "index")
  = link_to "#{review.book.title}", book_path(review.book.id)
.username-review-block
  %h5.username-title
    = link_to("#{review.user.username}", user_path(review.user.id))
    \: #{review.rating} #{star_color(review.rating)}
  %small.text-secondary (Отзывов: #{review.user.reviews.count})
%p.text-justify.review-body= review.body
.row.review-edit-block
  .col
    %p
      - if can? :manage, review
        = link_to '<i class="fa fa-edit ri"></i>'.html_safe, edit_book_review_path(review.book.id, review.id), title: "Редактировать"
        = link_to '<i class="fa fa-trash ri"></i>'.html_safe, book_review_path(review.book.id, review.id), method: :delete, data: { confirm: 'Вы уверены?' }, title: "Удалить"
  .col
    %p.text-right
      %small.text-secondary= review.created_at.strftime("%d.%m.%y %M:%H")
%hr

app/views/reviews/edit.html.haml
%h1 Редактировать отзыв
= render 'form', review: @review

app/views/reviews/index.html.haml
%h3.mb-4=link_to @book.title, book_path(@book.id)
%p Читали? Поделитесь своим мнением.
= link_to "Написать отзыв", new_book_review_path(@book.id), class: 'btn btn-primary btn-add-review'
%hr
.ml-3
  = render partial: 'reviews/review', collection: @reviews

app/views/reviews/new.html.haml
%h3 Отзыв для "#{@review.book.title}"
= render 'form', review: @review

app/views/reviews/show.html.haml
%p#notice= notice
%p
  %strong Body:
  = @review.body
%p
  %strong Rating:
  = @review.rating
%p
  %strong User:
  = @review.user
%p
  %strong Book:
  = @review.book
= link_to 'Edit', edit_review_path(@review)
|
= link_to 'Back', reviews_path